### 测试热交换
GET http://127.0.0.1:8080/net/test/hot/swap
Accept: application/json

### 存储 Redis 信息
POST http://127.0.0.1:8080/net/test/redis/save
Content-Type: application/json

{
  "redisKey": "jomkieRedisKey",
  "redisValue": "Jomkie love Linux."
}

### 获取 Redis 信息
GET http://127.0.0.1:8080/net/test/redis/get/jomkieRedisKey
Accept: application/json

### 删除 Redis 信息
GET http://127.0.0.1:8080/net/test/redis/delete/jomkieRedisKey
Accept: application/json

### 测试 GET 回调
GET http://www.xxx.xxx/net/test/remote/get/Linux
Accept: application/json

### 测试 POST 回调
POST http://www.xxx.xxx/net/test/remote/post
Content-Type: application/json

{"username":  "Jomkie", "age":  27}


### 测试微信支付接口
GET http://127.0.0.1:8080/net/test/wechat/pay
Content-Type: application/json

### 获取微信支付平台证书
GET http://127.0.0.1:8080/net/test/get/wechat/platform
Accept: application/json