### 测试 GET 远程请求
GET http://www.jomchen.top/net/test/remote/get
Accept: application/json

### 测试 POST 远程请求
POST http://www.jomchen.top/net/test/remote/post
Content-Type: application/json

{"username":  "Jomkie", "age":  27}


### 测试微信支付接口
GET http://localhost:8080/net/test/wechat/pay
Content-Type: application/json
