### 更新用户
POST http://127.0.0.1:8080/net/user/update
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "name": "李寻欢2",
  "age": 42,
  "email": "googlemail2@gmail.com",
  "dateTime": "2020-01-01"
}

### 增加用户
POST http://127.0.0.1:8080/net/user/add
Content-Type: application/json

{
  "id": 1,
  "name": "李寻欢",
  "age": 400,
  "email": "googlemail@gmail.com",
  "dateTime": "2020-01-01"
}

### 删除用户
GET http://127.0.0.1:8080/net/user/del/1
Accept: application/json

### 根据用户id查询用户
GET http://127.0.0.1:8080/net/user/getOne/1
Accept: application/json
